"""
recommender.py
==============
Phase 4, part 1: turning three analyses into one suggested action.

Phases 2 and 3 each answer a different question about a process - what kind of
thing it is, whether it is behaving abnormally, and where it is heading.  This
module reads all three and answers the practical question: *should a human do
something about it?*

    classification (Phase 2) ─┐
    anomaly check  (Phase 3) ─┼─► Recommendation(action, reason, confidence)
    trend forecast (Phase 3) ─┘

Why this module never acts
--------------------------
This is the design decision to be ready to defend in the demo, so the
reasoning is spelled out here rather than in a comment somewhere:

1. **The model's labels are not ground truth.**  The classifier was trained on
   labels generated by a threshold rule (see model.py), so "CPU_INTENSIVE" is
   a statement about numbers, not about intent.  A video encoder pinned at
   100 % CPU is doing exactly its job; so is a compiler.  Nothing in the
   feature set - CPU, memory, thread count - can tell those apart from a
   runaway process.
2. **The actions are not symmetric.**  Being wrong about "no action needed"
   costs nothing; being wrong about "suspend" can cost somebody hours of
   unsaved work.  When the downside is that lopsided, the correct design puts
   a human in the loop rather than tuning a threshold until it feels safe.
3. **The user knows things the model cannot see.**  That 4 GB process might be
   a render the user started deliberately two minutes ago.  The dashboard has
   no way to know that, and the user needs no explanation at all.
4. **Accountability.**  Every action is taken by a person who confirmed a
   dialog, and it is written to data/action_log.csv with their reason.  An
   automatic system leaves nobody to ask.

So this module returns advice.  process_manager.py performs actions, and only
when the GUI has confirmed one with the user.  The two are separate files on
purpose: nothing in this module can execute anything even by accident.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Optional, Sequence

from anomaly import KIND_MEMORY_LEAK
from predictor_trend import KIND_MEMORY_GROWTH
from process_manager import (ACTION_LOWER_PRIORITY, ACTION_SUSPEND,
                             is_protected, protection_reason)

# These mirror model.LABELS.  They are duplicated here as plain strings so the
# recommender keeps working on a machine without scikit-learn installed -
# importing model.py would drag in the whole ML stack.
LABEL_CPU_INTENSIVE = "CPU_INTENSIVE"
LABEL_MEMORY_INTENSIVE = "MEMORY_INTENSIVE"

# Actions that are only advice - process_manager has no method for them.
ACTION_NONE = "No action needed"
ACTION_MONITOR = "Monitor"

# How sure the classifier has to be before its label is worth acting on.  A
# 60 %-confidence "CPU_INTENSIVE" is the forest hedging between two classes,
# which is not a basis for changing a process's scheduling priority.
HIGH_CONFIDENCE = 80.0

# Confidence floors for the advisory outcomes (see Recommendation.confidence).
MONITOR_CONFIDENCE = 65.0
MONITOR_CONFIDENCE_BOTH = 80.0     # anomaly *and* trend agree
DEFAULT_CONFIDENCE = 90.0
SUSPEND_CONFIDENCE_CAP = 95.0      # never fully certain about a destructive act

SUSPEND_WARNING = (
    "Suspending freezes every thread in the process. It cannot save, respond "
    "or finish what it is doing, and it stays frozen until it is resumed. "
    "Unsaved work may be lost."
)
LOWER_PRIORITY_WARNING = (
    "The process keeps running and keeps its data; it just gets less CPU time "
    "when the machine is busy. This can be undone from Task Manager."
)


@dataclass
class Recommendation:
    """What the engine suggests for one process, and why."""

    action: str
    reason: str
    # 0-100.  This is a transparent rule-based score, NOT a probability from a
    # model: it reports how much evidence the triggering rule had.  For an
    # action driven by the classifier it is the classifier's own confidence;
    # for advisory outcomes it is a fixed value documented above.
    confidence: float

    # Extra text the GUI puts in the confirmation dialog.  Empty for advice.
    warning: str = ""
    # True only when process_manager has a matching method.  "Monitor" and
    # "No action needed" are advice, so nothing can be applied for them.
    executable: bool = False
    # True when the process is on the protected list, so the GUI can explain
    # why an obviously busy process has no suggestion.
    protected: bool = False


def recommend(process,
              prediction=None,
              anomaly_result=None,
              forecast=None) -> Recommendation:
    """
    Decide what, if anything, should be done about one process.

    Every argument except ``process`` is optional: with the ML stack missing
    or the model untrained this still returns a sensible "No action needed"
    rather than failing.
    """
    # --- rule 0: protected processes get no suggestions at all ------------
    # Checked first so that no amount of anomalous-looking behaviour can
    # produce a suggestion to interfere with csrss.exe.  process_manager
    # enforces the same list again when an action is actually attempted.
    if is_protected(process.pid, process.name):
        return Recommendation(
            ACTION_NONE,
            protection_reason(process.pid, process.name) or "Protected process",
            DEFAULT_CONFIDENCE,
            protected=True)

    label = prediction.label if prediction is not None else None
    confidence = prediction.confidence if prediction is not None else 0.0

    is_anomaly = anomaly_result is not None and anomaly_result.is_anomaly
    # The strict leak signal: memory rose in five consecutive samples with no
    # dip (anomaly.py).  The trend fitter's "memory_growth" is a softer signal
    # - a positive slope - so it alone is not enough to suggest suspending
    # something.  When only that fires we fall through to Monitor.
    leak_detected = (anomaly_result is not None
                     and anomaly_result.kind == KIND_MEMORY_LEAK)
    trend_warning = forecast is not None and forecast.has_warning
    growth_trend = forecast is not None and forecast.kind == KIND_MEMORY_GROWTH

    # --- rule 1: a memory hog that is also leaking ------------------------
    # Two independent signals agreeing - the classifier calls it memory heavy
    # *and* the leak heuristic sees monotonic growth - is the only case that
    # justifies suggesting the destructive action.
    if label == LABEL_MEMORY_INTENSIVE and leak_detected:
        return Recommendation(
            ACTION_SUSPEND,
            f"Classified MEMORY_INTENSIVE ({confidence:.0f}% confidence) and "
            f"memory is growing steadily - {anomaly_result.reason}",
            min(SUSPEND_CONFIDENCE_CAP, (confidence + 100.0) / 2.0),
            warning=SUSPEND_WARNING,
            executable=True)

    # --- rule 2: a confident CPU hog --------------------------------------
    # Lowering priority is safe and reversible, so the bar is the classifier
    # being confident rather than two signals agreeing.
    if label == LABEL_CPU_INTENSIVE and confidence >= HIGH_CONFIDENCE:
        # The reason strings start with an acronym ("CPU 4.1x above...") so
        # they are spliced in as-is rather than case-adjusted.
        detail = ""
        if is_anomaly:
            detail = f"; {anomaly_result.reason}"
        elif trend_warning:
            detail = f"; {forecast.message}"
        return Recommendation(
            ACTION_LOWER_PRIORITY,
            f"Classified CPU_INTENSIVE ({confidence:.0f}% confidence){detail}. "
            f"Lowering priority frees CPU for foreground work without stopping it",
            confidence,
            warning=LOWER_PRIORITY_WARNING,
            executable=True)

    # --- rule 3: something is off, but not enough to act on ---------------
    if is_anomaly or trend_warning:
        reasons = []
        if is_anomaly:
            reasons.append(anomaly_result.reason)
        if trend_warning:
            reasons.append(forecast.message)
        score = (MONITOR_CONFIDENCE_BOTH if (is_anomaly and trend_warning)
                 else MONITOR_CONFIDENCE)
        note = ("Watch this one - it is unusual but not clearly a problem"
                if not growth_trend else
                "Watch this one - memory is climbing but has not met the leak test")
        return Recommendation(
            ACTION_MONITOR,
            f"{'; '.join(reasons)}. {note}",
            score)

    # --- rule 4: nothing to report ----------------------------------------
    if label:
        reason = f"Classified {label} ({confidence:.0f}% confidence), behaving normally"
        score = confidence
    else:
        reason = "Behaving normally"
        score = DEFAULT_CONFIDENCE
    return Recommendation(ACTION_NONE, reason, score)


def recommend_all(processes: Sequence,
                  predictions: Optional[Dict] = None,
                  anomalies: Optional[Dict] = None,
                  forecasts: Optional[Dict] = None) -> Dict[int, Recommendation]:
    """Run :func:`recommend` across a whole snapshot, keyed by PID."""
    predictions = predictions or {}
    anomalies = anomalies or {}
    forecasts = forecasts or {}
    return {
        process.pid: recommend(process,
                               predictions.get(process.pid),
                               anomalies.get(process.pid),
                               forecasts.get(process.pid))
        for process in processes
    }


# ---------------------------------------------------------------------------
# Manual test:  python recommender.py
#
# Uses synthetic inputs so every rule is exercised, including the ones that
# depend on conditions that are rare on a healthy machine.
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    from anomaly import AnomalyResult, KIND_MEMORY_SPIKE
    from monitor import ProcessInfo
    from predictor import Prediction
    from predictor_trend import Forecast, KIND_MEMORY_GROWTH as GROWTH

    def make(pid=4242, name="demo.exe", cpu=1.0, mem=100.0):
        return ProcessInfo(pid=pid, name=name, cpu_percent=cpu, memory_mb=mem,
                           thread_count=8, priority="Normal", status="running")

    leak = AnomalyResult(True, "Memory increasing for 5 consecutive samples - "
                               "possible leak (+240.0 MB)", KIND_MEMORY_LEAK, 240.0)
    spike = AnomalyResult(True, "CPU 4.1x above baseline (12.3 % vs 3.0 % average)",
                          KIND_MEMORY_SPIKE, 4.1)
    quiet = AnomalyResult(False, "Normal for demo.exe", "normal")
    growth = Forecast(True, "Memory trending upward (+180 MB/min) - check for leak",
                      GROWTH, 0.0, 180.0)
    steady = Forecast(False, "No significant trend", "none")

    cases = [
        ("memory hog + leak -> Suspend",
         make(), Prediction("MEMORY_INTENSIVE", 91.0), leak, growth),
        ("cpu hog, confident -> Lower Priority",
         make(), Prediction("CPU_INTENSIVE", 96.0), spike, steady),
        ("cpu hog, unsure -> falls through",
         make(), Prediction("CPU_INTENSIVE", 62.0), quiet, steady),
        ("anomalous only -> Monitor",
         make(), Prediction("NORMAL", 99.0), spike, steady),
        ("trend only -> Monitor",
         make(), Prediction("NORMAL", 99.0), quiet, growth),
        ("memory hog, growth trend but no strict leak -> Monitor",
         make(), Prediction("MEMORY_INTENSIVE", 88.0), quiet, growth),
        ("all quiet -> No action",
         make(), Prediction("NORMAL", 100.0), quiet, steady),
        ("protected process, wildly anomalous -> No action",
         make(pid=888, name="csrss.exe", cpu=99.0),
         Prediction("CPU_INTENSIVE", 100.0), leak, growth),
        ("no ML at all -> No action",
         make(), None, None, None),
    ]

    for title, process, prediction, found, forecast in cases:
        result = recommend(process, prediction, found, forecast)
        print(f"\n{title}")
        print(f"   action     : {result.action}"
              f"{'  [executable]' if result.executable else ''}"
              f"{'  [protected]' if result.protected else ''}")
        print(f"   confidence : {result.confidence:.1f} %")
        print(f"   reason     : {result.reason}")
